[phases.setup]
nixPkgs = ["php", "phpPackages.composer", "nodejs"]

[phases.setup.env]
phpExtensions = ["gd"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm install",
  "npm run build"
]

[phases.build]
cmds = [
  "php artisan key:generate --force",
  "php artisan config:clear",
  "php artisan config:cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
